### ISSUE TITLE
not able to render ui page when deploying using own s3 bucket

### ISSUE THREAD

**Issue by AManandmathur** [aws-samples/aws-lex-web-ui#128] opened 2018-11-28 03:22 UTC
We are deploying the Lex web UI using own bootstrap bucket but unable to render the UI page. Stack created successfully without error but UI doesn’t render.

**Comment by bobpskier** [comment] 2018-11-28 14:57
I'm wondering if the problem is build environment related. Please take a look at this comment to a prior issue. https://github.com/aws-samples/aws-lex-web-ui/issues/110#issuecomment-439278309. Could you try a build and upload to your s3 bucket using a Cloud9 IDE following these steps to see if it resolves the problem.

**Comment by AManandmathur** [comment] 2018-12-03 03:45
I am able to use only master branch, why is it necessary to use development branch, i want to change the shade of the red color appearing in the output page.

**Comment by AManandmathur** [comment] 2018-12-03 03:46
Thanks I was able to deploy using cloud9 but I am able to use only master branch, why is it necessary to use development branch, i want to change the shade of the red color appearing in the output page.

**Comment by bobpskier** [comment] 2018-12-05 02:12
You should be able to use either branch after cloning the repo by checking out the appropriate branch. The git commands for this repo would be "git checkout development" or "git checkout master". This would let you switch back and forth. However you won't be able to commit changes back to this particular repo owned within aws-samples. 

Instead you can "fork" the repo to your own GitHub repo from which to work on. You would then be free to commit changes to either branch on your own repo. Typically we would use the "development" branch to develop new features which would then be merged back on the the "master" branch to release as a new version. The intent is to keep the master version always working without any problems introduced. 

To commit your own changes specific to your needs take a look at the "fork" button / feature available in GitHub to create your own repo. Using a "fork" you will be able to change the css on the master branch and commit / deploy as needed. You could also use the same process we use, testing on a "development" branch and merging back to your own "master" branch when ready to release.  If you have multiple developers this approach is probably recommended. If it is just yourself doing all the work, sticking with the master branch is a simpler approach to use.  

If you have additional questions, let me know.

**Closed as completed** 2024-03-18 20:19 UTC
