### ISSUE TITLE
User/Bot interaction messages show up out of order for the agent

### ISSUE THREAD

**Issue by sen-aws** [aws-samples/aws-lex-web-ui#513] opened 2023-04-23 22:27 UTC
I have a customer  who is using the QnABot from the AWS Solutions Library ([https://aws.amazon.com/solutions/implementations/qnabot-on-aws/ ](https://aws.amazon.com/solutions/implementations/qnabot-on-aws/)) 
When they connect the QnABot to Amazon Connect Agent, the User/Bot interaction messages show up out of order for the agent. 
For example, 
- 3/5
- 1/5 
- 2/5
- 4/5
- 5/5

Will it be fixed in the future versions so that the messages always show up in the correct order (1/5 through 5/5)?

**Comment by bobpskier** [comment] 2023-04-23 23:28
@sen-aws It has never been a problem in the past. I assume the incorrect messages are delivered after an agent has accepted the live chat and has seen the prior chat transcript. Attached is a small screen capture that I just ran demonstrating correct message order between lex-web-ui and connect.

https://user-images.githubusercontent.com/11319101/233871411-12a3fd97-a7b0-40d5-9ee8-ad8d0755b633.mp4

One of the items you can verify in the browser debugger network tab is the order of messages sent to livechat. Look for the POST requests against the participant.connect api and the "message" File. The request payload will contain the message content. I my example messages are sent in the order the user has entered them and show up in the default CCP properly.

if the messages are sent in the proper order, you'll need to look at the CCP code to understand how its receiving and displaying these. If they are not sent in the proper order please grab a screen capture / movie of the browser behavior along with the order of the POST requests for messages. We can try and debug from there. 

Does this happen 100% of the time?
What version of lex-web-ui are you using?
What CCP are you using?
What AWS region are you using

**Comment by sen-aws** [comment] 2023-04-24 23:35
I will ask them to provide the details.

**Comment by gbaskin98** [comment] 2023-04-26 20:53
@bobpskier 
- This does not happen 100% of the time. But it will occasionally happen for the longer conversations (5 messages, 11 messages, and I've seen 16 messages end up out of order). 
- We are using the v0.19.6 version. 
- We are using the default Amazon connect CCP, not a custom one. 
- We have everything deployed in the Oregon (us-west-2) region.

**Comment by bobpskier** [comment] 2023-04-27 02:41
@gbaskin98 Thanks for the update. I hope we can figure out what might be happening. From a version and deployment everything looks good and should work fine in us-west-2.

We still need a bit better description to see if we can home in on the problem component. 

Can you tell us if the agent is handling multiple chats when the problem appears? 

If the agent is handling multiple chats, does the problem appear after tabbing back to the chat in question? And up until tabbing back, does the conversation look correct?

If the agent is only in a single chat, does the conversation start out correct and then at some point the existing messages get out of order?

It would be great if we could get a little better synopsis of the problem such as:

"The agent accepts a chat and reviews the transcript of qnabot interactions by the user. The agent starts to converse with the user. All looks good for the first 5 messages. When the user sends the sixth message, messages in the default CCP are no longer ordered correctly. The first message is displayed after the fourth message. After the first occurrence, the ordering is correct until some point in the future where the user enters the 16th message, this now appears earlier in the list than the 15th message."

or something like

"The agent accepts a chat and views the transcript of qnabot interactions. The user has already entered five messages during live chat startup and Immediately the default CCP shows incorrect ordering of messages. The user's first message was placed after the fourth message in the UI" .

We need to get a feel for how the problem manifests itself and how the agent is using the CCP when this occurs. 

The lex-web-ui uses an api provided by Connect that sends a message every time the user clicks the send button in the UI. I've never seen it behave any other way. Without seeing output from the browser debugger, its difficult to believe anything different is happening. It should be sending a message per user button click as the user enters these. This is how its coded. It also indicates to Connect via API that the user has started entering new text so that the agent can see the user is typing. 

With this assumption, the ordering of messages displayed is the responsibility of the Connect back end and the default CCP as the UI.

Is the problem somewhat reproduce able? That is, if you shared the URL for lext-web-ui with me, could we test a live chat that one of your agents accepts as a test to confirm proper lex-web-ui behavior?

Have you submitted an AWS support case to the Amazon Connect team to get their involvement in troubleshooting this problem with message ordering in the CCP?

**Comment by bobpskier** [comment] 2023-05-02 19:30
@billsnyder All is well. Same to you. Thanks for indicating its a problem with the transcript and not the subsequent conversation. My understanding is that the transcript is sent in multiple requests due to a payload size limit in the connect api.  The send mechanism in the browser is asynchronous in behavior. The delay was introduced to try and work around problems in the connect implementation maintaining proper ordering of messages. Introducing synchronous behavior becomes problematic with a larger transcript sizes. You don't want to freeze the UI waiting for connect to respond. Your choices are to increase this delay to some level that connect mostly keeps the transcript ordered properly. Seems like it is pretty close as the problem is infrequent. Or work with the connect team to keep proper ordering of messages delivered to the CCP as they are sent by the browser.

**Comment by billsnyder** [comment] 2023-05-02 21:30
@bobpskier Do you think a PR that surfaces the delay as a variable that could be set/updated via a CloudFormation parameter would be accepted?  This would allow users to control the delay without needing to maintain a fork of the repo.  I'll work the connect route first but may want to explore that option as well.

**Comment by bobpskier** [comment] 2023-05-02 22:37
@billsnyder It make sense to have this configurable. I can work out the mechanism to make the delay configurable via CF template parameter and submit a PR.

**Comment by billsnyder** [comment] 2023-05-02 23:44
Thank you!

**Comment by bobpskier** [comment] 2023-05-03 15:34
Pull request submitted. https://github.com/aws-samples/aws-lex-web-ui/pull/514

**Comment by atjohns** [comment] 2023-05-03 15:57
PR has been merged into development and will go out in the next release probably around the end of the month.

**Comment by atjohns** [comment] 2023-05-22 18:30
This fix has been pushed out with the latest release

**Closed by atjohns** 2023-05-22 18:30 UTC
