### ISSUE TITLE
Creating Stack for Lex V2

### ISSUE THREAD

**Issue by amitdubay** [aws-samples/aws-lex-web-ui#333] opened 2021-11-03 05:51 UTC
I am trying to create the stack for an existing Lex V2 Bot, but the CFT template gives an error when leaving the botAlias value as blank. If I provide the V2 alias name, it does create all the resources but adds the botName in the config file from V2BotId. The Web UI is working after it is deployed, however it's connecting to the V1 APIs. When I manually update the config file and remove the botId and botAlias as it should only have the V2 parameters, then the Web UI tries to connect to the Bot and runs into a timeout issue.

Please let me know how to create the web app with just the V2 parameters. Thank you!

![image](https://user-images.githubusercontent.com/2901901/140014865-cf7bbaab-4939-4b96-974f-c28bd052ddba.png)

**Comment by bobpskier** [comment] 2021-11-03 15:58
Adjust the Lex V2 parameters in the template when deploying. 

![lexv2setup](https://user-images.githubusercontent.com/11319101/140096023-e9d07e44-d881-4e41-950a-9b956540c4fa.png)

**Comment by amitdubay** [comment] 2021-11-03 16:43
Thank you @bobpskier for the response. I deleted the old stack and created a brand new one leaving the botName as blank and botAlias as $LATEST as specified in the screenshot. I just provided the V2BotId and V2BotAlias. You may notice that the config file in the deployed web app has botName and botAlias populated hence it's connecting to V1.

![image](https://user-images.githubusercontent.com/2901901/140104304-5282dc40-f7d4-47da-82af-1558c0dfa596.png)

You can try the newly created web app using the link below, just say 'hi' and it will return a V1 response card that wont be rendered on the UI.

https://d2pz0kvvx72zx2.cloudfront.net/parent.html

**Comment by bobpskier** [comment] 2021-12-18 15:51
The existence of a value in v2BotId  is going to control whether the UI connects to LexV2 or LexV1. The botName is a required element and is just a duplicate of v2BotId. The templates create specific roles in Cognito for V2 or V1 based on configuration values. Please reopen the issue if not connection to your desired Lex bot.

**Closed by bobpskier** 2021-12-18 15:51 UTC
